### ISSUE TITLE
Issue after submitting ZIP

### ISSUE THREAD

**Issue by gorsuch** [anoopr/flood#3]
Howdy!  I'm going to do more investigation, but figure I'd open this here for tracking purposes if you do not mind.

I setup flood and am using [this list](https://foursquare.com/michaelgorsuch/list/flooddemo).  After I do a `RESET`, the app asks for my ZIP.  I send it back and the following exception occurs:

```
NoMethodError (undefined method `[]' for nil:NilClass):
lib/message_processor.rb:26:in `block in process_message_from_person'
lib/message_processor.rb:25:in `times'
lib/message_processor.rb:25:in `process_message_from_person'
app/controllers/twilio_controller.rb:8:in `receive'
```

I am currently assuming that I have misconfigured something on the Foursquare side of things.  Going to dig a little later tonight.

**Comment by anoopr** [comment]
I’m guessing it’s because there’s not any items on the list. Try adding a few places to it and give it another go.

**Comment by gorsuch** [comment]
Actually, now would be a great time for you to help me understand what the list is for in the first place ;-)

Can you help me or point me to some docs / code that would help clarify?  I'm happy to do any writing necessary.

**Comment by gorsuch** [comment]
Ah, okay, after actually reading the code, this makes a lot more sense to me.  Is `Venue` supposed to represent an affected area or something like that?

**Comment by gorsuch** [comment]
I'll get a console going in a bit and debug those bits.

**Comment by anoopr** [comment]
Here's what it's supposed to do: http://www.youtube.com/watch?v=gWaIcXVYg30

Basically the Foursquare list is volunteer sites. When you text your zip code, it will return the three closest venues on that list. You can then select one and it will associate your phone number with that volunteer site, and someone running that site can text you further instructions. It's super lightweight, but there's a lot of obvious things that could be built on top of it. I just wanted to make something that would work when the only infrastructure available was SMS

**Comment by gorsuch** [comment]
:heart: - this makes so much sense.  This is a good platform concept.

**Comment by gorsuch** [comment]
@anoopr any chance I can get you to add exactly what you just wrote to the README?  Super useful and makes everything obvious.

**Comment by gorsuch** [comment]
Ahh, I see what's going on here.  At least 3 locations much exist.  Added the 3rd location and things are looking better.

**Comment by gorsuch** [comment]
Closing this out since the general issue has been resolved.
